### ISSUE TITLE
master  branch  unavailable

### ISSUE THREAD

**Issue by sosoyososo** [mattgallagher/CwlPreconditionTesting#9] opened 2017-03-13 23:53 UTC
Just as title described , code on master branch can't pass building and branch swift2.3 can be used with swift 2.2 。 

macOS 10.11.6 / Xcode 7.3 & 8.2 test ~

**Comment by mattgallagher** [comment] 2017-03-14 01:31
There were some path issues in the "master" branch that might have caused include files to load in the wrong order, causing problems. These should be fixed in the latest:

https://github.com/mattgallagher/CwlPreconditionTesting/tree/433d3ddb451128783222f322ba6e57601d9af3d6

However, I'm not able to reproduce any problems on the swift2.3 branch using Xcode 7.3.1 and swift 2.2 with the exception of selecting an iOS build with the Mac as the build device (you need to select an iOS device).

If you can include the build errors you're seeing, then I can investigate further.

**Comment by sosoyososo** [comment] 2017-03-14 09:29
Sorry for language problems,  maybe I should just make a list : 
1 . Branch Swift2.3 is all good , but problem is it can be used with swift2.2 。 
2. Branch master build fail with swift2.2 in Xcode7.3 .
> a . Dependency files CwlCatchException(.h .m .swift) are not shown on this branch .
> b. Xcode shown issue were  FetchDependencies script error 。
> c. I just add CwlCatchException files from branch swift2.3 to master,   build framework itself failed ,but build it within my own test project succeed 。

**Closed as completed** 2018-05-26 07:05 UTC
